### ISSUE TITLE
Calling toDouble() on null

### ISSUE THREAD

**Issue by Friiiis** [pedromassango/titled_navigation_bar#10]
The onTap() callback of triggers a the PageView to jump to the clicked page, which somehow causes toDouble() to be called on null. 

The wierd thing is, that after the error gets thrown, I can change the onTap() to just print out the index, hot reload, and then change the onTap() back to the below code. This will make everything work. But the initial load will trigger this error.

Code to replicate:
```
class _MainPageState extends State<MainPage> {
  PageController pageController;

  void bottomNavigationTapped(int index) {
      pageController.jumpToPage(index);
  }

  @override
  void initState() {
    pageController = PageController(initialPage: 0);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: colorPicker.getPrimary(),
      body: body(),
      bottomNavigationBar: TitledBottomNavigationBar(
        indicatorColor:Colors.black,
        activeColor: Colors.black,
        inactiveColor: Colors.black45,
        initialIndex: 0,
        currentIndex: currentIndex,
        onTap: (index) {
          bottomNavigationTapped(index);
        },
        items: [
          TitledNavigationBarItem(
            title: 'PAGE 1',
            icon: Icons.home,
          ),
          TitledNavigationBarItem(
            title: 'PAGE 2',
            icon: Icons.home,
          ),
        ],
      ),
    );
  }

  Widget body() {
    return PageView(
      physics: NeverScrollableScrollPhysics(),
      controller: pageController,
      children: <Widget>[
        Center(
          child: Text('Page 1'),
        ),
        Center(
          child: Text('Page 2'),
        ),
      ],
    );
  }
}

```

Debug console:
```
Restarted application in 2,207ms.
I/flutter ( 2691): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2691): The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(411.4,
I/flutter ( 2691): 820.6), devicePixelRatio: 2.6, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
I/flutter ( 2691): EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
I/flutter ( 2691): true, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false)):
I/flutter ( 2691): The method 'toDouble' was called on null.
I/flutter ( 2691): Receiver: null
I/flutter ( 2691): Tried calling: toDouble()
I/flutter ( 2691):
I/flutter ( 2691): When the exception was thrown, this was the stack:
I/flutter ( 2691): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 2691): #1      double.*  (dart:core-patch/double.dart:33:23)
I/flutter ( 2691): #2      _PagePosition.getPixelsFromPage 
I/flutter ( 2691): #3      PageController.jumpToPage 
I/flutter ( 2691): #4      _MainPageState.bottomNavigationTapped.<anonymous closure>
I/flutter ( 2691): #5      State.setState 
I/flutter ( 2691): #6      _MainPageState.bottomNavigationTapped
I/flutter ( 2691): #7      _MainPageState.build.<anonymous closure>
I/flutter ( 2691): #8      _TitledBottomNavigationBarState._select
I/flutter ( 2691): #9      _TitledBottomNavigationBarState.initState
I/flutter ( 2691): #10     StatefulElement._firstBuild 
I/flutter ( 2691): #11     ComponentElement.mount 
I/flutter ( 2691): #12     Element.inflateWidget 
I/flutter ( 2691): #13     Element.updateChild 
I/flutter ( 2691): #14     ComponentElement.performRebuild 
I/flutter ( 2691): #15     Element.rebuild 
I/flutter ( 2691): #16     ComponentElement._firstBuild 
I/flutter ( 2691): #17     ComponentElement.mount 
I/flutter ( 2691): #18     Element.inflateWidget 
I/flutter ( 2691): #19     Element.updateChild 
I/flutter ( 2691): #20     ComponentElement.performRebuild 
I/flutter ( 2691): #21     Element.rebuild 
I/flutter ( 2691): #22     ComponentElement._firstBuild 
I/flutter ( 2691): #23     ComponentElement.mount 
I/flutter ( 2691): #24     ParentDataElement.mount 
I/flutter ( 2691): #25     Element.inflateWidget 
I/flutter ( 2691): #26     MultiChildRenderObjectElement.mount 
I/flutter ( 2691): #27     Element.inflateWidget 
I/flutter ( 2691): #28     Element.updateChild 
I/flutter ( 2691): #29     ComponentElement.performRebuild 
I/flutter ( 2691): #30     Element.rebuild 
I/flutter ( 2691): #31     ComponentElement._firstBuild 
I/flutter ( 2691): #32     StatefulElement._firstBuild 
I/flutter ( 2691): #33     ComponentElement.mount 
I/flutter ( 2691): #34     Element.inflateWidget 
I/flutter ( 2691): #35     Element.updateChild 
I/flutter ( 2691): #36     ComponentElement.performRebuild 
I/flutter ( 2691): #37     Element.rebuild 
I/flutter ( 2691): #38     ComponentElement._firstBuild 
I/flutter ( 2691): #39     ComponentElement.mount 
I/flutter ( 2691): #40     Element.inflateWidget 
I/flutter ( 2691): #41     Element.updateChild 
I/flutter ( 2691): #42     ComponentElement.performRebuild 
I/flutter ( 2691): #43     Element.rebuild 
I/flutter ( 2691): #44     ComponentElement._firstBuild 
I/flutter ( 2691): #45     StatefulElement._firstBuild 
I/flutter ( 2691): #46     ComponentElement.mount 
I/flutter ( 2691): #47     Element.inflateWidget 
I/flutter ( 2691): #48     Element.updateChild 
I/flutter ( 2691): #49     SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #50     Element.inflateWidget 
I/flutter ( 2691): #51     Element.updateChild 
I/flutter ( 2691): #52     ComponentElement.performRebuild 
I/flutter ( 2691): #53     Element.rebuild 
I/flutter ( 2691): #54     ComponentElement._firstBuild 
I/flutter ( 2691): #55     ComponentElement.mount 
I/flutter ( 2691): #56     Element.inflateWidget 
I/flutter ( 2691): #57     Element.updateChild 
I/flutter ( 2691): #58     SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #59     Element.inflateWidget 
I/flutter ( 2691): #60     Element.updateChild 
I/flutter ( 2691): #61     ComponentElement.performRebuild 
I/flutter ( 2691): #62     Element.rebuild 
I/flutter ( 2691): #63     ComponentElement._firstBuild 
I/flutter ( 2691): #64     StatefulElement._firstBuild 
I/flutter ( 2691): #65     ComponentElement.mount 
I/flutter ( 2691): #66     Element.inflateWidget 
I/flutter ( 2691): #67     Element.updateChild 
I/flutter ( 2691): #68     ComponentElement.performRebuild 
I/flutter ( 2691): #69     Element.rebuild 
I/flutter ( 2691): #70     ComponentElement._firstBuild 
I/flutter ( 2691): #71     StatefulElement._firstBuild 
I/flutter ( 2691): #72     ComponentElement.mount 
I/flutter ( 2691): #73     Element.inflateWidget 
I/flutter ( 2691): #74     Element.updateChild 
I/flutter ( 2691): #75     ComponentElement.performRebuild 
I/flutter ( 2691): #76     Element.rebuild 
I/flutter ( 2691): #77     ComponentElement._firstBuild 
I/flutter ( 2691): #78     ComponentElement.mount 
I/flutter ( 2691): #79     Element.inflateWidget 
I/flutter ( 2691): #80     Element.updateChild 
I/flutter ( 2691): #81     ComponentElement.performRebuild 
I/flutter ( 2691): #82     Element.rebuild 
I/flutter ( 2691): #83     ComponentElement._firstBuild 
I/flutter ( 2691): #84     ComponentElement.mount 
I/flutter ( 2691): #85     Element.inflateWidget 
I/flutter ( 2691): #86     Element.updateChild 
I/flutter ( 2691): #87     ComponentElement.performRebuild 
I/flutter ( 2691): #88     Element.rebuild 
I/flutter ( 2691): #89     ComponentElement._firstBuild 
I/flutter ( 2691): #90     StatefulElement._firstBuild 
I/flutter ( 2691): #91     ComponentElement.mount 
I/flutter ( 2691): #92     Element.inflateWidget 
I/flutter ( 2691): #93     Element.updateChild 
I/flutter ( 2691): #94     ComponentElement.performRebuild 
I/flutter ( 2691): #95     Element.rebuild 
I/flutter ( 2691): #96     ComponentElement._firstBuild 
I/flutter ( 2691): #97     StatefulElement._firstBuild 
I/flutter ( 2691): #98     ComponentElement.mount 
I/flutter ( 2691): #99     Element.inflateWidget 
I/flutter ( 2691): #100    Element.updateChild 
I/flutter ( 2691): #101    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #102    Element.inflateWidget 
I/flutter ( 2691): #103    Element.updateChild 
I/flutter ( 2691): #104    ComponentElement.performRebuild 
I/flutter ( 2691): #105    Element.rebuild 
I/flutter ( 2691): #106    ComponentElement._firstBuild 
I/flutter ( 2691): #107    ComponentElement.mount 
I/flutter ( 2691): #108    Element.inflateWidget 
I/flutter ( 2691): #109    Element.updateChild 
I/flutter ( 2691): #110    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #111    Element.inflateWidget 
I/flutter ( 2691): #112    Element.updateChild 
I/flutter ( 2691): #113    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #114    Element.inflateWidget 
I/flutter ( 2691): #115    Element.updateChild 
I/flutter ( 2691): #116    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #117    Element.inflateWidget 
I/flutter ( 2691): #118    Element.updateChild 
I/flutter ( 2691): #119    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #120    Element.inflateWidget 
I/flutter ( 2691): #121    Element.updateChild 
I/flutter ( 2691): #122    ComponentElement.performRebuild 
I/flutter ( 2691): #123    Element.rebuild 
I/flutter ( 2691): #124    ComponentElement._firstBuild 
I/flutter ( 2691): #125    StatefulElement._firstBuild 
I/flutter ( 2691): #126    ComponentElement.mount 
I/flutter ( 2691): #127    Element.inflateWidget 
I/flutter ( 2691): #128    Element.updateChild 
I/flutter ( 2691): #129    ComponentElement.performRebuild 
I/flutter ( 2691): #130    Element.rebuild 
I/flutter ( 2691): #131    ComponentElement._firstBuild 
I/flutter ( 2691): #132    ComponentElement.mount 
I/flutter ( 2691): #133    Element.inflateWidget 
I/flutter ( 2691): #134    Element.updateChild 
I/flutter ( 2691): #135    ComponentElement.performRebuild 
I/flutter ( 2691): #136    Element.rebuild 
I/flutter ( 2691): #137    ComponentElement._firstBuild 
I/flutter ( 2691): #138    StatefulElement._firstBuild 
I/flutter ( 2691): #139    ComponentElement.mount 
I/flutter ( 2691): #140    Element.inflateWidget 
I/flutter ( 2691): #141    Element.updateChild 
I/flutter ( 2691): #142    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #143    Element.inflateWidget 
I/flutter ( 2691): #144    Element.updateChild 
I/flutter ( 2691): #145    ComponentElement.performRebuild 
I/flutter ( 2691): #146    Element.rebuild 
I/flutter ( 2691): #147    ComponentElement._firstBuild 
I/flutter ( 2691): #148    ComponentElement.mount 
I/flutter ( 2691): #149    Element.inflateWidget 
I/flutter ( 2691): #150    Element.updateChild 
I/flutter ( 2691): #151    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #152    Element.inflateWidget 
I/flutter ( 2691): #153    Element.updateChild 
I/flutter ( 2691): #154    ComponentElement.performRebuild 
I/flutter ( 2691): #155    Element.rebuild 
I/flutter ( 2691): #156    ComponentElement._firstBuild 
I/flutter ( 2691): #157    StatefulElement._firstBuild 
I/flutter ( 2691): #158    ComponentElement.mount 
I/flutter ( 2691): #159    Element.inflateWidget 
I/flutter ( 2691): #160    Element.updateChild 
I/flutter ( 2691): #161    ComponentElement.performRebuild 
I/flutter ( 2691): #162    Element.rebuild 
I/flutter ( 2691): #163    ComponentElement._firstBuild 
I/flutter ( 2691): #164    ComponentElement.mount 
I/flutter ( 2691): #165    Element.inflateWidget 
I/flutter ( 2691): #166    Element.updateChild 
I/flutter ( 2691): #167    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #168    Element.inflateWidget 
I/flutter ( 2691): #169    Element.updateChild 
I/flutter ( 2691): #170    ComponentElement.performRebuild 
I/flutter ( 2691): #171    Element.rebuild 
I/flutter ( 2691): #172    ComponentElement._firstBuild 
I/flutter ( 2691): #173    ComponentElement.mount 
I/flutter ( 2691): #174    Element.inflateWidget 
I/flutter ( 2691): #175    Element.updateChild 
I/flutter ( 2691): #176    ComponentElement.performRebuild 
I/flutter ( 2691): #177    Element.rebuild 
I/flutter ( 2691): #178    ComponentElement._firstBuild 
I/flutter ( 2691): #179    StatefulElement._firstBuild 
I/flutter ( 2691): #180    ComponentElement.mount 
I/flutter ( 2691): #181    Element.inflateWidget 
I/flutter ( 2691): #182    Element.updateChild 
I/flutter ( 2691): #183    ComponentElement.performRebuild 
I/flutter ( 2691): #184    Element.rebuild 
I/flutter ( 2691): #185    ComponentElement._firstBuild 
I/flutter ( 2691): #186    StatefulElement._firstBuild 
I/flutter ( 2691): #187    ComponentElement.mount 
I/flutter ( 2691): #188    Element.inflateWidget 
I/flutter ( 2691): #189    MultiChildRenderObjectElement.mount 
I/flutter ( 2691): #190    Element.inflateWidget 
I/flutter ( 2691): #191    Element.updateChild 
I/flutter ( 2691): #192    _TheatreElement.mount 
I/flutter ( 2691): #193    Element.inflateWidget 
I/flutter ( 2691): #194    Element.updateChild 
I/flutter ( 2691): #195    ComponentElement.performRebuild 
I/flutter ( 2691): #196    Element.rebuild 
I/flutter ( 2691): #197    ComponentElement._firstBuild 
I/flutter ( 2691): #198    StatefulElement._firstBuild 
I/flutter ( 2691): #199    ComponentElement.mount 
I/flutter ( 2691): #200    Element.inflateWidget 
I/flutter ( 2691): #201    Element.updateChild 
I/flutter ( 2691): #202    ComponentElement.performRebuild 
I/flutter ( 2691): #203    Element.rebuild 
I/flutter ( 2691): #204    ComponentElement._firstBuild 
I/flutter ( 2691): #205    ComponentElement.mount 
I/flutter ( 2691): #206    Element.inflateWidget 
I/flutter ( 2691): #207    Element.updateChild 
I/flutter ( 2691): #208    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #209    Element.inflateWidget 
I/flutter ( 2691): #210    Element.updateChild 
I/flutter ( 2691): #211    ComponentElement.performRebuild 
I/flutter ( 2691): #212    Element.rebuild 
I/flutter ( 2691): #213    ComponentElement._firstBuild 
I/flutter ( 2691): #214    StatefulElement._firstBuild 
I/flutter ( 2691): #215    ComponentElement.mount 
I/flutter ( 2691): #216    Element.inflateWidget 
I/flutter ( 2691): #217    Element.updateChild 
I/flutter ( 2691): #218    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #219    Element.inflateWidget 
I/flutter ( 2691): #220    Element.updateChild 
I/flutter ( 2691): #221    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #222    Element.inflateWidget 
I/flutter ( 2691): #223    Element.updateChild 
I/flutter ( 2691): #224    ComponentElement.performRebuild 
I/flutter ( 2691): #225    Element.rebuild 
I/flutter ( 2691): #226    ComponentElement._firstBuild 
I/flutter ( 2691): #227    StatefulElement._firstBuild 
I/flutter ( 2691): #228    ComponentElement.mount 
I/flutter ( 2691): #229    Element.inflateWidget 
I/flutter ( 2691): #230    Element.updateChild 
I/flutter ( 2691): #231    ComponentElement.performRebuild 
I/flutter ( 2691): #232    Element.rebuild 
I/flutter ( 2691): #233    ComponentElement._firstBuild 
I/flutter ( 2691): #234    ComponentElement.mount 
I/flutter ( 2691): #235    Element.inflateWidget 
I/flutter ( 2691): #236    Element.updateChild 
I/flutter ( 2691): #237    ComponentElement.performRebuild 
I/flutter ( 2691): #238    Element.rebuild 
I/flutter ( 2691): #239    ComponentElement._firstBuild 
I/flutter ( 2691): #240    ComponentElement.mount 
I/flutter ( 2691): #241    Element.inflateWidget 
I/flutter ( 2691): #242    Element.updateChild 
I/flutter ( 2691): #243    ComponentElement.performRebuild 
I/flutter ( 2691): #244    Element.rebuild 
I/flutter ( 2691): #245    ComponentElement._firstBuild 
I/flutter ( 2691): #246    ComponentElement.mount 
I/flutter ( 2691): #247    Element.inflateWidget 
I/flutter ( 2691): #248    Element.updateChild 
I/flutter ( 2691): #249    ComponentElement.performRebuild 
I/flutter ( 2691): #250    Element.rebuild 
I/flutter ( 2691): #251    ComponentElement._firstBuild 
I/flutter ( 2691): #252    ComponentElement.mount 
I/flutter ( 2691): #253    Element.inflateWidget 
I/flutter ( 2691): #254    Element.updateChild 
I/flutter ( 2691): #255    ComponentElement.performRebuild 
I/flutter ( 2691): #256    Element.rebuild 
I/flutter ( 2691): #257    ComponentElement._firstBuild 
I/flutter ( 2691): #258    ComponentElement.mount 
I/flutter ( 2691): #259    Element.inflateWidget 
I/flutter ( 2691): #260    Element.updateChild 
I/flutter ( 2691): #261    ComponentElement.performRebuild 
I/flutter ( 2691): #262    Element.rebuild 
I/flutter ( 2691): #263    ComponentElement._firstBuild 
I/flutter ( 2691): #264    ComponentElement.mount 
I/flutter ( 2691): #265    Element.inflateWidget 
I/flutter ( 2691): #266    Element.updateChild 
I/flutter ( 2691): #267    ComponentElement.performRebuild 
I/flutter ( 2691): #268    Element.rebuild 
I/flutter ( 2691): #269    ComponentElement._firstBuild 
I/flutter ( 2691): #270    StatefulElement._firstBuild 
I/flutter ( 2691): #271    ComponentElement.mount 
I/flutter ( 2691): #272    Element.inflateWidget 
I/flutter ( 2691): #273    Element.updateChild 
I/flutter ( 2691): #274    ComponentElement.performRebuild 
I/flutter ( 2691): #275    Element.rebuild 
I/flutter ( 2691): #276    ComponentElement._firstBuild 
I/flutter ( 2691): #277    ComponentElement.mount 
I/flutter ( 2691): #278    Element.inflateWidget 
I/flutter ( 2691): #279    Element.updateChild 
I/flutter ( 2691): #280    ComponentElement.performRebuild 
I/flutter ( 2691): #281    Element.rebuild 
I/flutter ( 2691): #282    ComponentElement._firstBuild 
I/flutter ( 2691): #283    ComponentElement.mount 
I/flutter ( 2691): #284    Element.inflateWidget 
I/flutter ( 2691): #285    Element.updateChild 
I/flutter ( 2691): #286    ComponentElement.performRebuild 
I/flutter ( 2691): #287    Element.rebuild 
I/flutter ( 2691): #288    ComponentElement._firstBuild 
I/flutter ( 2691): #289    ComponentElement.mount 
I/flutter ( 2691): #290    Element.inflateWidget 
I/flutter ( 2691): #291    Element.updateChild 
I/flutter ( 2691): #292    ComponentElement.performRebuild 
I/flutter ( 2691): #293    Element.rebuild 
I/flutter ( 2691): #294    ComponentElement._firstBuild 
I/flutter ( 2691): #295    ComponentElement.mount 
I/flutter ( 2691): #296    Element.inflateWidget 
I/flutter ( 2691): #297    Element.updateChild 
I/flutter ( 2691): #298    ComponentElement.performRebuild 
I/flutter ( 2691): #299    Element.rebuild 
I/flutter ( 2691): #300    ComponentElement._firstBuild 
I/flutter ( 2691): #301    ComponentElement.mount 
I/flutter ( 2691): #302    Element.inflateWidget 
I/flutter ( 2691): #303    Element.updateChild 
I/flutter ( 2691): #304    SingleChildRenderObjectElement.mount 
I/flutter ( 2691): #305    Element.inflateWidget 
I/flutter ( 2691): #306    Element.updateChild 
I/flutter ( 2691): #307    ComponentElement.performRebuild 
I/flutter ( 2691): #308    Element.rebuild 
I/flutter ( 2691): #309    ComponentElement._firstBuild 
I/flutter ( 2691): #310    StatefulElement._firstBuild 
I/flutter ( 2691): #311    ComponentElement.mount 
I/flutter ( 2691): #312    Element.inflateWidget 
I/flutter ( 2691): #313    Element.updateChild 
I/flutter ( 2691): #314    ComponentElement.performRebuild 
I/flutter ( 2691): #315    Element.rebuild 
I/flutter ( 2691): #316    ComponentElement._firstBuild 
I/flutter ( 2691): #317    ComponentElement.mount 
I/flutter ( 2691): #318    Element.inflateWidget 
I/flutter ( 2691): #319    Element.updateChild 
I/flutter ( 2691): #320    ComponentElement.performRebuild 
I/flutter ( 2691): #321    Element.rebuild 
I/flutter ( 2691): #322    ComponentElement._firstBuild 
I/flutter ( 2691): #323    ComponentElement.mount 
I/flutter ( 2691): #324    Element.inflateWidget 
I/flutter ( 2691): #325    Element.updateChild 
I/flutter ( 2691): #326    ComponentElement.performRebuild 
I/flutter ( 2691): #327    Element.rebuild 
I/flutter ( 2691): #328    ComponentElement._firstBuild 
I/flutter ( 2691): #329    StatefulElement._firstBuild 
I/flutter ( 2691): #330    ComponentElement.mount 
I/flutter ( 2691): #331    Element.inflateWidget 
I/flutter ( 2691): #332    Element.updateChild 
I/flutter ( 2691): #333    ComponentElement.performRebuild 
I/flutter ( 2691): #334    Element.rebuild 
I/flutter ( 2691): #335    ComponentElement._firstBuild 
I/flutter ( 2691): #336    ComponentElement.mount 
I/flutter ( 2691): #337    Element.inflateWidget 
I/flutter ( 2691): #338    Element.updateChild 
I/flutter ( 2691): #339    ComponentElement.performRebuild 
I/flutter ( 2691): #340    Element.rebuild 
I/flutter ( 2691): #341    ComponentElement._firstBuild 
I/flutter ( 2691): #342    StatefulElement._firstBuild 
I/flutter ( 2691): #343    ComponentElement.mount 
I/flutter ( 2691): #344    Element.inflateWidget 
I/flutter ( 2691): #345    Element.updateChild 
I/flutter ( 2691): #346    ComponentElement.performRebuild 
I/flutter ( 2691): #347    Element.rebuild 
I/flutter ( 2691): #348    ComponentElement._firstBuild 
I/flutter ( 2691): #349    ComponentElement.mount 
I/flutter ( 2691): #350    Element.inflateWidget 
I/flutter ( 2691): #351    Element.updateChild 
I/flutter ( 2691): #352    RenderObjectToWidgetElement._rebuild 
I/flutter ( 2691): #353    RenderObjectToWidgetElement.mount 
I/flutter ( 2691): #354    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
I/flutter ( 2691): #355    BuildOwner.buildScope 
I/flutter ( 2691): #356    RenderObjectToWidgetAdapter.attachToRenderTree 
I/flutter ( 2691): #357    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
I/flutter ( 2691): #358    runApp 
I/flutter ( 2691): #359    main
I/flutter ( 2691): #360    _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:216:25)
I/flutter ( 2691): #365    _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:208:5)
I/flutter ( 2691): #366    _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 2691): #367    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 2691): (elided 4 frames from package dart:async)
I/flutter ( 2691): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by pedromassango** [comment]
Fixed, please update to the latest version

**Comment by Friiiis** [comment]
Thanks for the update, and sorry for the late response.
But I just tried again with the same setup and the error still gets thrown. I have updated the plugin and flutter to the latest version.
It's probably an error I'm causing myself, but i can't figure out why though.
